# This is a basic workflow to help you get started with Actions

name: Build React App and Deploy to S3

# Controls when the workflow will run
on:
  pull_request:
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install 
        
      - name: Build React App
        run: npm run build
        
      - name: Deploy to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{secrets.AWS_KEY_ID}}
          aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{secrets.S3_BUCKET}}
          source_dir: 'build/'
      

